### ISSUE TITLE
[Battle] Improvement: Update quest if requirements match

### ISSUE THREAD

**Issue by filipemeneses** [generic-game/generic-game#2]
**Improvement:** Make relationship between quest and killing things

**Description:** When a character posses a quest that required killing something, then when the character kills, must update the quest accordingly.

**Expected behaviours:**

```js
describe('quest', () => {
  test('should update once requirement is done')
})
```

**Comment by theTechie** [comment]
@filipemeneses - do we now have a way to describe if a quest involves `killing something`?

As per my understanding of the source, i see that only way to detect a killing is by checking if someone was involved in a conflict and if ended up `!isAlive()`.
But, i do not see a way for a quest leading to a fight?

What's your idea behind this?

**Comment by filipemeneses** [comment]
@theTechie - first, thanks for the interest. And yea, we can describe `killing something` that is checking `!isAlive()` after a `character.battle.conflict` or an `character.battle.attack`.

When the quest is built, is defined steps to accomplish it. Each step may request killing some creatures, where, once completed the character receives the reward.

Now, after a conflict or an attack to some other character, automatically updating the quest would be interesting.
