### ISSUE TITLE
Equipment spelling

### ISSUE THREAD

**Issue by ZophieWinters** [generic-game/generic-game#5]
Currently "Equipment" is spelled as "Equipament" - not sure if this is intentional or not, I guess this is how it is spelled in Catalan but the more common English spelling is "Equipment".

Also I really like what you're creating here, good work so far it is very useful!

**Comment by filipemeneses** [comment]
Oh, you're right. I will fix that as soon as possible. Thanks for the observation!

I'm glad you're enjoying. :+1:

**Comment by filipemeneses** [comment]
Updated in: cdcf3e09b17f5dee2adc6f2995eb6eaa8bb51e13
Published as `0.2.3`

Thanks for the collaboration 😄
